### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm-web#14]
I think a search for the website is practical.
This way somebody can easily check, whether gbm officially supports the games one want to back up / track.
I have already implemented a very bacsic search in my fork.
`tag:gog` checks the icons in the list, might change that to real tags.
I don’t think it would be usefil to search for other attributes, GBM is  better for that.
Any ideas, what else I should add?

https://basxto.github.io/gbm-web/GBM_Official.xml

**Comment by MikeMaximus** [comment]
Looks great basxto, more user friendly to have it right on the page than relying on people using built-in browser search.  A name and tag search is enough I'd think.  I can't really think of anything else, i'd probably just add a Search label and an extra space between the input box and the first entry.

**Comment by basxto** [comment]
What I plan on doing:
* Filter option for tracking only (not part of real tags)
* Clickable tags
* Linkable searches like `GBM_Official.xml#q=wide%20tag:floss`, which allows to use back and forward buttons in browser ([jhash](https://archive.codeplex.com/?p=jhash))
* Collapse all when searching
* Uncollapse if only one match
* Allow to exclude like `-tag:steamcloud` `-war`
* Allow `id:` for permalinks

I just used a primitive input box for getting started.
I think it would also make sense to offset it on the left, so it is in line with the titles.

**Comment by MikeMaximus** [comment]
Sounds good!  I'm not sure what you mean by clickable tags.  Do you mean so they can click them to add to search filter?

**Comment by basxto** [comment]
Yes, clicking on a tag would add it to the search field.

**Comment by basxto** [comment]
Linking games works now:

https://basxto.github.io/gbm-web/GBM_Official.xml#?q=id:bfe9fe20-0ab2-4205-a586-eb2cf771131e
