### ISSUE TITLE
Add "Report" link to official list

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm-web#16]
I've noticed that some older configurations on the official Windows list are broken because GOG updated their installers.  This mostly affects DOSBox/ScummVM configurations.

Adding a "Report Broken Configuration" link on the official list may be useful.  I was thinking simply a mailto link with a custom subject.

**Comment by basxto** [comment]
How about something like this:
https://github.com/MikeMaximus/gbm-web/issues/new?title=[Broken%20Linux]%200%20AD&body=https://mikemaximus.github.io/gbm-web/GBM_Official_Linux.xml%23?q=id:bbf8e00a-d7b8-46a5-b52c-8ba886b8c38a%0D%0A*automatically%20generated*%0D%0A%23%23%20The%20following%20is%20not%20working:%0D%0A

That would create an issue with a permalink to the configuration.

**Edit:**
You need an github account for that. But `mailto:`-links also only work for those, who use e-mail clients.

**Comment by MikeMaximus** [comment]
I kinda like the issue idea instead of email.
