### ISSUE TITLE
[Broken Wine] Fallout Shelter

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm-web#18]
https://mikemaximus.github.io/gbm-web/GBM_Official.xml#?q=id:bbb7b1a1-5cd2-4ffd-85fb-fd443b3e424d

For me it’s `%LOCALAPPDATA%\FalloutShelter`

**Comment by MikeMaximus** [comment]
Thanks.  I haven't played that since it was exclusive to Bethesda's client.  Maybe it was changed when ported to Steam.

**Comment by basxto** [comment]
Since it’s tagged `steam`, freeware and among the officially supported proton games,  I thought you might have used that for testing.

**Comment by MikeMaximus** [comment]
I'm not sure when I put the Steam tag on it, but I shouldn't have cause i didn't test it.

I used Inside, No Man's Sky, Fallout: New Vegas and some others for testing.

**Comment by MikeMaximus** [comment]
Fixed for next list update.
