### ISSUE TITLE
Switch to pure CSS tree menu

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm-web#2]
It seems be possible getting the game lists working without JavaScript

https://codepen.io/bisserof/pen/fdtBm

**Comment by MikeMaximus** [comment]
Neat,  i'll take a look.

**Comment by MikeMaximus** [comment]
Thanks for the tip.  That code is so much cleaner.  

I'll get around to redoing the menu without javascript too.

**Comment by basxto** [comment]
For that it might be helpful using [jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/), it seems github has native support for that. But I’m not completely sure.
Or are just talking about the dropdowns menus?

**Comment by MikeMaximus** [comment]
Just the drop-down menu.
