### ISSUE TITLE
Super Galaxy Squadron EX Turbo triggering from system process

### ISSUE THREAD

**Issue by DasKatzchen** [MikeMaximus/gbm-web#29]
The target process for Super Galaxy Squadron EX Turbo is "runner". On Arch Linux the search indexing process is named "baloorunner" and is constantly triggering GBM.

**Comment by MikeMaximus** [comment]
Thanks for the report. "Regular Expression" is enabled on that game's configuration for some reason, it shouldn't be.

**Comment by DasKatzchen** [comment]
That's what I thought, but I don't have the game so I couldn't check if it was set to that for a reason

**Comment by MikeMaximus** [comment]
That configuration was from another contributor so I'm not entirely sure myself.  But I think it's a safe assumption that it's a mistake since it doesn't include any regular expression syntax.

**Comment by MikeMaximus** [comment]
This is taken care of in the recent list update.
