### ISSUE TITLE
Using uniform icons

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm-web#9]
Maybe it would look better to use uniform icons from [Icons8](https://icons8.com/license/) or so.
(The icons are black on transparent, so I added background and round corner with css)

![2018-06-21_17 09_181x360](https://user-images.githubusercontent.com/1314450/41728035-1ec83626-7576-11e8-97c4-aa493616f890.png)

Bad thing is, that even they don’t have icons for anything. But new icons can be requested.
Lacking so far:
* DOSBox
* SCUMMVM
* Itch.io
* Humble

**Comment by MikeMaximus** [comment]
Yeah it would look nicer if they were all the same color scheme.  I can probably do the missing ones myself in GIMP.

**Comment by MikeMaximus** [comment]
I forgot about this after my colossal failure at making my own versions of the missing icons in GIMP.  Maybe we just can just use similar looking ones and make a legend.

**Comment by MikeMaximus** [comment]
I've changed the existing icons to more unified looking grayscale theme, it doesn't look as nice as a truly uniform theme but I think it's much better than it was.
